root: true
extends:
  - '@atomix'
rules:
  no-console: 0
  valid-typeof: 0
  prettier/prettier: 0
  prefer-rest-params: 0
  unicorn/filename-case: 0
  class-methods-use-this: 0
  no-useless-constructor: 0
  import/no-default-export: 0
  space-before-function-paren: 0
